/* tslint:disable */
/**
 * This file was automatically generated by Payload CMS.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    media: Media;
    posts: Post;
    users: User;
  };
  globals: {};
}
export interface Media {
  id: string;
  alt: string;
  darkModeFallback?: string | Media;
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
  width?: number;
  height?: number;
  createdAt: string;
  updatedAt: string;
}
export interface Post {
  id: string;
  title: string;
  image: string | Media;
  excerpt: {
    [k: string]: unknown;
  }[];
  content: (
    | {
        bannerFields: {
          type?: 'default' | 'success' | 'warning' | 'error';
          addCheckmark?: boolean;
          content: {
            [k: string]: unknown;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'banner';
      }
    | {
        blogContentFields: {
          richText: {
            [k: string]: unknown;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'blogContent';
      }
    | {
        codeFields: {
          language?: 'none' | 'js' | 'ts';
          code: string;
        };
        id?: string;
        blockName?: string;
        blockType: 'code';
      }
    | {
        blogMarkdownFields: {
          markdown: string;
        };
        id?: string;
        blockName?: string;
        blockType: 'blogMarkdown';
      }
    | {
        mediaBlockFields: {
          position?: 'default' | 'wide';
          media: string | Media;
          caption?: {
            [k: string]: unknown;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'mediaBlock';
      }
  )[];
  slug?: string;
  publishedOn: string;
  _status?: 'draft' | 'published';
  createdAt: string;
  updatedAt: string;
}
export interface User {
  id: string;
  firstName: string;
  lastName: string;
  roles: ('admin' | 'public')[];
  email?: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  loginAttempts?: number;
  lockUntil?: string;
  createdAt: string;
  updatedAt: string;
  password?: string;
}
